const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_MOVIES: 'FETCH_MOVIES',
    FETCH_MOVIE: 'FETCH_MOVIE',
    SET_MOVIE: 'SET_MOVIE',
    POST_REVIEW: 'POST_REVIEW',
    FETCH_VIDEOS: 'FETCH_VIDEOS',
    SET_VIDEO: 'SET_VIDEO',
    FETCH_COMMENTS: 'FETCH_COMMENTS',
    POST_COMMENT: 'POST_COMMENT'
}

export default Constants;